import dns from "node:dns";
dns.setServers(['8.8.8.8','8.8.4.4'])

import { Geist, Oswald, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "animate.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const oswaldSans = Oswald({
  weight:'400',
  subsets: ["latin"],
});

export const metadata = {
  title: "SunCart – Summer Essentials Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className={`${oswaldSans.className} min-h-full flex flex-col`}>
        <Navbar ></Navbar>
        <main >
          {children}
          <ToastContainer position="top-center"></ToastContainer>
        </main>
        <Footer></Footer>
        </body>
    </html>
  );
}
